# config/packages/vich_uploader.yaml

vich_uploader:
    db_driver: orm
    mappings:
        products:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: false
